(()=>{
  const installInsurance=()=>{
    const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
    const todayIso=()=>new Date().toISOString().slice(0,10);
    const dateLabel=value=>value?new Date(value+'T12:00:00').toLocaleDateString('en-US'):'Not entered';
    const monthlyAmount=policy=>Number(policy.premium||0)*({Monthly:1,Quarterly:1/3,'Semiannual':1/6,Annual:1/12}[policy.frequency]||0);
    const categories=['All','Life Insurance','Home Insurance','Auto Insurance','Health Insurance','Miscellaneous'];
    const healthTypes=['Medical','Dental','Vision','Other Health'];
    state.insurancePolicies=Array.isArray(state.insurancePolicies)?state.insurancePolicies:[];
    state.householdChildren=Array.isArray(state.householdChildren)?state.householdChildren:[];
    state.insuranceView=state.insuranceView||'All';

    const nav=$('#nav'),assetNav=nav.querySelector('[data-page="Physical Assets"]');
    if(!nav.querySelector('[data-page="Insurance"]'))assetNav.insertAdjacentHTML('beforebegin','<button data-page="Insurance" data-icon="shield-check"><i data-lucide="shield-check"></i>Insurance</button>');

    const page=document.createElement('section');page.id='insurancePage';page.className='insurance-page';page.innerHTML=`
      <div class="module-intro"><div><h2 class="module-title">Insurance</h2><div class="module-copy">Household policies, covered people and assets, carrier contacts, cards, and policy documentation.</div></div><button class="primary-btn" id="newInsurancePolicy"><i data-lucide="plus"></i> Add policy</button></div>
      <div class="insurance-category-tabs" id="insuranceCategoryTabs"></div>
      <div class="grid insurance-kpis"><article class="card"><span>Active policies</span><strong id="insuranceActiveCount">0</strong></article><article class="card"><span>Monthly premium equivalent</span><strong id="insuranceMonthlyPremium">$0</strong></article><article class="card"><span>Renewing in 60 days</span><strong id="insuranceRenewalCount">0</strong></article><article class="card"><span>Stored documents & cards</span><strong id="insuranceDocumentCount">0</strong></article></div>
      <article class="card browser-storage-notice"><i data-lucide="hard-drive"></i><div><strong>Temporary browser document storage</strong><div>Attachments are saved only in this browser until the secure database is connected. Keep original policy documents elsewhere.</div></div></article>
      <div class="insurance-policy-list" id="insurancePolicyList"></div>`;
    $('#physicalAssetsPage').before(page);

    document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="insuranceModal"><form class="modal insurance-modal" id="insuranceForm"><div class="modal-head"><div><h2 id="insuranceModalTitle">Add insurance policy</h2><div class="card-note">Policy, carrier, covered household members or assets, and browser-stored documents.</div></div><button class="close-btn" type="button" data-close-insurance><i data-lucide="x"></i></button></div><input type="hidden" id="insurancePolicyId"><div class="form-grid">
      <div class="field"><label>Insurance category</label><select id="insuranceCategory" required>${categories.slice(1).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field" id="insuranceHealthTypeField"><label>Health coverage type</label><select id="insuranceHealthType">${healthTypes.map(x=>`<option>${x}</option>`).join('')}</select></div>
      <div class="field"><label>Policy name</label><input id="insurancePolicyName" required></div><div class="field"><label>Policy number</label><input id="insurancePolicyNumber"></div>
      <div class="field full form-section-label">Insurance company & contact</div><div class="field"><label>Company name</label><input id="insuranceCompany" required></div><div class="field"><label>Agent / contact name</label><input id="insuranceAgent"></div><div class="field"><label>Contact phone</label><input id="insurancePhone" type="tel"></div><div class="field"><label>Contact email</label><input id="insuranceEmail" type="email"></div><div class="field full"><label>Company / agent address</label><input id="insuranceAddress"></div>
      <div class="field full form-section-label">Coverage & cost</div><div class="field"><label>Coverage amount</label><input id="insuranceCoverage" type="number" min="0" step=".01"></div><div class="field"><label>Premium</label><input id="insurancePremium" type="number" min="0" step=".01"></div><div class="field"><label>Premium frequency</label><select id="insuranceFrequency"><option>Monthly</option><option>Quarterly</option><option>Semiannual</option><option>Annual</option></select></div><div class="field"><label>Payment account</label><select id="insurancePaymentAccount"></select></div><div class="field check-field"><input id="insuranceAutopay" type="checkbox"><label for="insuranceAutopay">Autopay enabled</label></div><div class="field"><label>Status</label><select id="insuranceStatus"><option>Active</option><option>Pending</option><option>Expired</option><option>Archived</option></select></div>
      <div class="field"><label>Effective date</label><input id="insuranceEffective" type="date"></div><div class="field"><label>Renewal date</label><input id="insuranceRenewal" type="date"></div><div class="field"><label>Expiration date</label><input id="insuranceExpiration" type="date"></div>
      <div class="field full" id="insuranceAssetField"><label id="insuranceAssetLabel">Covered asset</label><select id="insuranceAsset"></select></div><div class="field full" id="insurancePeopleField"><label>Covered household members</label><div class="insurance-person-choices" id="insurancePeople"></div></div>
      <div class="field full"><label>Policy documents / insurance cards</label><input id="insuranceAttachments" type="file" accept="image/*,.pdf" multiple><div class="field-help">Images or PDFs, maximum 1.5 MB each. Files remain only in this browser during the prototype phase.</div><div id="existingInsuranceAttachments"></div></div>
      <div class="field full"><label>Notes</label><textarea id="insuranceNotes"></textarea></div></div><div class="modal-foot"><button class="danger-btn" id="deleteInsurancePolicy" type="button">Delete</button><div class="modal-actions"><button class="secondary-btn" type="button" data-close-insurance>Cancel</button><button class="primary-btn" type="submit">Save policy</button></div></div></form></div>`);

    const personOptions=()=>[
      ...state.householdUsers.map(user=>({key:'user:'+user.id,name:user.displayName,type:'Household user'})),
      ...state.householdChildren.map(child=>({key:'child:'+child.id,name:[child.firstName,child.lastName].filter(Boolean).join(' '),type:'Child profile'}))
    ];
    const linkedName=key=>personOptions().find(person=>person.key===key)?.name||'Unknown household member';
    const assetsFor=category=>state.assets.filter(asset=>category==='Home Insurance'?asset.categoryId==='real-estate':category==='Auto Insurance'?asset.categoryId==='vehicles':false);
    const syncCarrier=(policy)=>{
      state.rolodexOrganizations=state.rolodexOrganizations||[];state.rolodexContacts=state.rolodexContacts||[];
      let company=state.rolodexOrganizations.find(item=>item.type==='Company'&&item.name.trim().toLowerCase()===policy.company.trim().toLowerCase());
      if(!company){company={id:'org-insurance-'+Date.now(),name:policy.company,type:'Company',businessCategory:'Insurance provider',address1:policy.contactAddress,email:policy.contactEmail,phone:policy.contactPhone,website:'',photoUrl:'',tagIds:[],notes:'Created from an insurance policy.',status:'active'};state.rolodexOrganizations.push(company)}
      else Object.assign(company,{address1:policy.contactAddress||company.address1,email:policy.contactEmail||company.email,phone:policy.contactPhone||company.phone});
      policy.rolodexOrganizationId=company.id;
      if(policy.agentName){let contact=policy.rolodexContactId&&state.rolodexContacts.find(item=>item.id===policy.rolodexContactId);const parts=policy.agentName.trim().split(/\s+/);if(!contact){contact={id:'contact-insurance-'+Date.now(),firstName:parts.shift()||policy.agentName,lastName:parts.join(' '),organizationIds:[company.id],title:'Insurance contact',email:policy.contactEmail,cellPhone:policy.contactPhone,status:'active',tagIds:[],notes:'Created from an insurance policy.'};state.rolodexContacts.push(contact)}else Object.assign(contact,{firstName:parts.shift()||policy.agentName,lastName:parts.join(' '),organizationIds:[company.id],email:policy.contactEmail,cellPhone:policy.contactPhone});policy.rolodexContactId=contact.id}
    };
    const readAttachments=async files=>{const output=[];for(const file of files){if(file.size>1572864)throw new Error(file.name+' exceeds the 1.5 MB browser-storage limit.');const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Could not read '+file.name));reader.readAsDataURL(file)});output.push({id:'insurance-file-'+Date.now()+'-'+output.length,name:file.name,type:file.type||'application/octet-stream',size:file.size,addedAt:new Date().toISOString(),dataUrl})}return output};
    const toggleFields=()=>{const category=$('#insuranceCategory').value,isHealth=category==='Health Insurance',usesPeople=isHealth||category==='Life Insurance',usesAsset=category==='Home Insurance'||category==='Auto Insurance';$('#insuranceHealthTypeField').style.display=isHealth?'grid':'none';$('#insurancePeopleField').style.display=usesPeople?'grid':'none';$('#insuranceAssetField').style.display=usesAsset?'grid':'none';if(usesAsset){$('#insuranceAssetLabel').textContent=category==='Home Insurance'?'Covered property':'Covered automobile';$('#insuranceAsset').innerHTML='<option value="">Select an asset</option>'+assetsFor(category).map(asset=>`<option value="${asset.id}">${esc(asset.name)}</option>`).join('')}};
    const attachmentRows=policy=>(policy.attachments||[]).map(file=>`<div class="insurance-file-row"><a href="${file.dataUrl}" download="${esc(file.name)}" target="_blank" rel="noopener"><i data-lucide="file-text"></i><span><strong>${esc(file.name)}</strong><small>${Math.ceil(file.size/1024)} KB · browser storage</small></span></a><button type="button" class="danger-btn" data-remove-insurance-file="${file.id}">Remove</button></div>`).join('');
    const openPolicy=id=>{const policy=id?state.insurancePolicies.find(item=>item.id===id):null;$('#insuranceForm').reset();$('#insurancePolicyId').value=policy?.id||'';$('#insuranceModalTitle').textContent=policy?'Edit '+policy.policyName:'Add insurance policy';$('#insuranceCategory').value=policy?.category||'Life Insurance';$('#insuranceHealthType').value=policy?.healthType||'Medical';$('#insurancePolicyName').value=policy?.policyName||'';$('#insurancePolicyNumber').value=policy?.policyNumber||'';$('#insuranceCompany').value=policy?.company||'';$('#insuranceAgent').value=policy?.agentName||'';$('#insurancePhone').value=policy?.contactPhone||'';$('#insuranceEmail').value=policy?.contactEmail||'';$('#insuranceAddress').value=policy?.contactAddress||'';$('#insuranceCoverage').value=policy?.coverageAmount||'';$('#insurancePremium').value=policy?.premium||'';$('#insuranceFrequency').value=policy?.frequency||'Monthly';$('#insurancePaymentAccount').innerHTML='<option value="">Not specified</option>'+state.accounts.filter(account=>account.type!=='creditCard').map(account=>`<option value="${account.id}" ${policy?.paymentAccountId===account.id?'selected':''}>${esc(account.nickname)}</option>`).join('');$('#insuranceAutopay').checked=policy?.autopay===true;$('#insuranceStatus').value=policy?.status||'Active';$('#insuranceEffective').value=policy?.effectiveDate||todayIso();$('#insuranceRenewal').value=policy?.renewalDate||'';$('#insuranceExpiration').value=policy?.expirationDate||'';$('#insuranceNotes').value=policy?.notes||'';$('#insurancePeople').innerHTML=personOptions().map(person=>`<label class="choice-check"><input type="checkbox" data-insurance-person="${person.key}" ${(policy?.coveredPersonIds||[]).includes(person.key)?'checked':''}> <span><strong>${esc(person.name)}</strong><small>${person.type}</small></span></label>`).join('')||'<div class="sub">Add household users or children in Settings first.</div>';toggleFields();$('#insuranceAsset').value=policy?.assetId||'';$('#existingInsuranceAttachments').innerHTML=attachmentRows(policy||{attachments:[]});$$('[data-remove-insurance-file]').forEach(button=>button.onclick=()=>{if(!policy)return;if(confirm('Remove this browser-stored attachment?')){policy.attachments=policy.attachments.filter(file=>file.id!==button.dataset.removeInsuranceFile);dataProvider.save(state);openPolicy(policy.id)}});$('#deleteInsurancePolicy').style.display=policy?'inline-flex':'none';$('#insuranceModal').classList.add('open');lucide.createIcons()};
    const policyCard=policy=>{const asset=state.assets.find(item=>item.id===policy.assetId),people=(policy.coveredPersonIds||[]).map(linkedName),company=state.rolodexOrganizations?.find(item=>item.id===policy.rolodexOrganizationId);return`<article class="card insurance-policy-card"><div class="insurance-policy-head"><div class="insurance-policy-icon"><i data-lucide="${policy.category==='Home Insurance'?'house':policy.category==='Auto Insurance'?'car':policy.category==='Health Insurance'?'heart-pulse':policy.category==='Life Insurance'?'umbrella':'shield'}"></i></div><div><span class="insurance-category">${esc(policy.healthType||policy.category)}</span><h2>${esc(policy.policyName)}</h2><div class="card-note">${esc(policy.company)}${policy.policyNumber?' · •••• '+esc(policy.policyNumber.slice(-4)):''}</div></div><span class="inventory-badge">${esc(policy.status)}</span></div><div class="insurance-policy-metrics"><div><span>Premium</span><strong>${money(policy.premium||0)} / ${esc(policy.frequency.toLowerCase())}</strong></div><div><span>Coverage</span><strong>${policy.coverageAmount?money(policy.coverageAmount):'See policy'}</strong></div><div><span>Renewal</span><strong>${dateLabel(policy.renewalDate)}</strong></div></div>${asset?`<div class="insurance-link"><i data-lucide="link"></i>Covered asset: <strong>${esc(asset.name)}</strong></div>`:''}${people.length?`<div class="insurance-link"><i data-lucide="users"></i>Covered: <strong>${people.map(esc).join(', ')}</strong></div>`:''}<div class="insurance-link"><i data-lucide="contact"></i>Rolodex: <strong>${esc(company?.name||policy.company)}</strong>${policy.agentName?' · '+esc(policy.agentName):''}</div>${(policy.attachments||[]).length?`<div class="insurance-doc-chips">${policy.attachments.map(file=>`<a href="${file.dataUrl}" target="_blank" rel="noopener" download="${esc(file.name)}"><i data-lucide="file-text"></i>${esc(file.name)}</a>`).join('')}</div>`:''}<div class="inventory-actions"><button class="primary-btn" data-edit-insurance="${policy.id}">Open policy</button>${company?`<button class="secondary-btn" data-open-insurance-company="${company.id}">Open company</button>`:''}</div></article>`};
    const renderInsurance=()=>{const active=state.insurancePolicies.filter(policy=>policy.status!=='Archived'),visible=active.filter(policy=>state.insuranceView==='All'||policy.category===state.insuranceView),in60=new Date;in60.setDate(in60.getDate()+60);$('#insuranceCategoryTabs').innerHTML=categories.map(category=>`<button class="${state.insuranceView===category?'active':''}" data-insurance-view="${category}">${category}<span>${category==='All'?active.length:active.filter(policy=>policy.category===category).length}</span></button>`).join('');$('#insuranceActiveCount').textContent=active.filter(policy=>policy.status==='Active').length;$('#insuranceMonthlyPremium').textContent=money(active.reduce((sum,policy)=>sum+monthlyAmount(policy),0));$('#insuranceRenewalCount').textContent=active.filter(policy=>policy.renewalDate&&new Date(policy.renewalDate+'T12:00')>=new Date&&new Date(policy.renewalDate+'T12:00')<=in60).length;$('#insuranceDocumentCount').textContent=active.reduce((sum,policy)=>sum+(policy.attachments||[]).length,0);$('#insurancePolicyList').innerHTML=visible.map(policyCard).join('')||'<article class="card insurance-empty"><i data-lucide="shield-plus"></i><strong>No policies in this category</strong><span>Add a policy when you are ready.</span></article>';$$('[data-insurance-view]').forEach(button=>button.onclick=()=>{state.insuranceView=button.dataset.insuranceView;dataProvider.save(state);renderInsurance()});$$('[data-edit-insurance]').forEach(button=>button.onclick=()=>openPolicy(button.dataset.editInsurance));$$('[data-open-insurance-company]').forEach(button=>button.onclick=()=>{setPage('Rolodex');setTimeout(()=>{state.rolodexView='crmCompanies';const search=$('#rolodexSearch');if(search){const company=state.rolodexOrganizations.find(item=>item.id===button.dataset.openInsuranceCompany);search.value=company?.name||'';search.dispatchEvent(new Event('input',{bubbles:true}))}},0)});lucide.createIcons()};

    $('#newInsurancePolicy').onclick=()=>openPolicy();$('#insuranceCategory').onchange=toggleFields;$$('[data-close-insurance]').forEach(button=>button.onclick=()=>$('#insuranceModal').classList.remove('open'));
    $('#insuranceForm').onsubmit=async event=>{event.preventDefault();const id=$('#insurancePolicyId').value,existing=id&&state.insurancePolicies.find(item=>item.id===id),saveButton=event.submitter;saveButton.disabled=true;try{const attachments=await readAttachments([...$('#insuranceAttachments').files]),policy=existing||{id:'insurance-'+Date.now(),attachments:[],createdAt:new Date().toISOString()};Object.assign(policy,{category:$('#insuranceCategory').value,healthType:$('#insuranceCategory').value==='Health Insurance'?$('#insuranceHealthType').value:'',policyName:$('#insurancePolicyName').value.trim(),policyNumber:$('#insurancePolicyNumber').value.trim(),company:$('#insuranceCompany').value.trim(),agentName:$('#insuranceAgent').value.trim(),contactPhone:$('#insurancePhone').value.trim(),contactEmail:$('#insuranceEmail').value.trim(),contactAddress:$('#insuranceAddress').value.trim(),coverageAmount:Number($('#insuranceCoverage').value)||0,premium:Number($('#insurancePremium').value)||0,frequency:$('#insuranceFrequency').value,paymentAccountId:$('#insurancePaymentAccount').value,autopay:$('#insuranceAutopay').checked,status:$('#insuranceStatus').value,effectiveDate:$('#insuranceEffective').value,renewalDate:$('#insuranceRenewal').value,expirationDate:$('#insuranceExpiration').value,assetId:['Home Insurance','Auto Insurance'].includes($('#insuranceCategory').value)?$('#insuranceAsset').value:'',coveredPersonIds:['Life Insurance','Health Insurance'].includes($('#insuranceCategory').value)?$$('[data-insurance-person]:checked').map(input=>input.dataset.insurancePerson):[],notes:$('#insuranceNotes').value.trim(),updatedAt:new Date().toISOString(),attachments:[...(policy.attachments||[]),...attachments]});syncCarrier(policy);if(!existing)state.insurancePolicies.push(policy);dataProvider.save(state);$('#insuranceModal').classList.remove('open');renderInsurance();showToast(policy.policyName+' saved.')}catch(error){alert(error.message)}finally{saveButton.disabled=false}};
    $('#deleteInsurancePolicy').onclick=()=>{const policy=state.insurancePolicies.find(item=>item.id===$('#insurancePolicyId').value);if(policy&&confirm('Permanently delete '+policy.policyName+' and its browser-stored attachments? The linked Rolodex company will be preserved.')){state.insurancePolicies=state.insurancePolicies.filter(item=>item.id!==policy.id);dataProvider.save(state);$('#insuranceModal').classList.remove('open');renderInsurance();showToast('Insurance policy deleted.')}};

    const syncChildContact=child=>{state.rolodexContacts=state.rolodexContacts||[];let contact=child.rolodexContactId&&state.rolodexContacts.find(item=>item.id===child.rolodexContactId);if(!contact){contact={id:'contact-child-'+Date.now(),status:'active',tagIds:[],organizationIds:[],notes:''};state.rolodexContacts.push(contact);child.rolodexContactId=contact.id}Object.assign(contact,{firstName:child.firstName,lastName:child.lastName,birthday:child.birthday,photoUrl:child.photoUrl,title:'Household child',notes:['School: '+(child.school||'Not entered'),'Sports: '+(child.sports||'Not entered'),'Hobbies: '+(child.hobbies||'Not entered'),'Social profiles: '+(child.socialProfiles||'Not entered')].join('\n')})};
    const openChild=id=>{const child=id?state.householdChildren.find(item=>item.id===id):null;openSimpleData(child?'Edit child profile':'Add child profile','Children can be covered by insurance and linked in the Rolodex, but never participate in financial calculations.',`<div class="field"><label>First name</label><input id="childFirstName" value="${esc(child?.firstName||'')}" required></div><div class="field"><label>Last name</label><input id="childLastName" value="${esc(child?.lastName||'')}" required></div><div class="field"><label>Birthday</label><input id="childBirthday" type="date" value="${child?.birthday||''}" required></div><div class="field"><label>School</label><input id="childSchool" value="${esc(child?.school||'')}"></div><div class="field"><label>Sports teams / activities</label><input id="childSports" value="${esc(child?.sports||'')}"></div><div class="field"><label>Hobbies</label><input id="childHobbies" value="${esc(child?.hobbies||'')}"></div><div class="field full"><label>Social media profiles</label><input id="childSocial" value="${esc(child?.socialProfiles||'')}" placeholder="Optional profile names or links"></div><div class="field full"><label>Photo link</label><input id="childPhoto" type="url" value="${esc(child?.photoUrl||'')}"></div><div class="field full"><label>Insurance / care notes</label><textarea id="childNotes">${esc(child?.notes||'')}</textarea></div>`,()=>{const record=child||{id:'child-'+Date.now(),createdAt:new Date().toISOString()};Object.assign(record,{firstName:$('#childFirstName').value.trim(),lastName:$('#childLastName').value.trim(),birthday:$('#childBirthday').value,school:$('#childSchool').value.trim(),sports:$('#childSports').value.trim(),hobbies:$('#childHobbies').value.trim(),socialProfiles:$('#childSocial').value.trim(),photoUrl:$('#childPhoto').value.trim(),notes:$('#childNotes').value.trim(),updatedAt:new Date().toISOString()});syncChildContact(record);if(!child)state.householdChildren.push(record);dataProvider.save(state);renderChildrenSettings();showToast(record.firstName+' profile saved.')})};
    const renderChildrenSettings=()=>{const panel=$('[data-settings-panel="household"]');if(!panel)return;let card=$('#householdChildrenCard');if(!card){card=document.createElement('article');card.id='householdChildrenCard';card.className='card section-gap';panel.append(card)}card.innerHTML=`<div class="card-head"><div><h2>Children</h2><div class="card-note">Family profiles for insurance and household reference. Children are linked to the Rolodex and excluded from all financial tracking.</div></div><button class="secondary-btn" id="addChildProfile"><i data-lucide="user-plus"></i> Add child</button></div><div class="child-profile-list">${state.householdChildren.map(child=>`<article class="child-profile-row"><div class="child-avatar">${child.photoUrl?`<img src="${esc(child.photoUrl)}" alt="${esc(child.firstName)}">`:esc((child.firstName[0]||'')+(child.lastName[0]||''))}</div><div><strong>${esc(child.firstName+' '+child.lastName)}</strong><div class="sub">Birthday ${dateLabel(child.birthday)}${child.school?' · '+esc(child.school):''}</div><span class="nonfinancial-tag">Not included in financial tracking</span></div><div class="child-actions"><button class="link-btn" data-edit-child="${child.id}">Edit</button><button class="danger-btn" data-delete-child="${child.id}">Delete</button></div></article>`).join('')||'<div class="sub">No child profiles have been added.</div>'}</div>`;$('#addChildProfile').onclick=()=>openChild();$$('[data-edit-child]').forEach(button=>button.onclick=()=>openChild(button.dataset.editChild));$$('[data-delete-child]').forEach(button=>button.onclick=()=>{const child=state.householdChildren.find(item=>item.id===button.dataset.deleteChild),covered=state.insurancePolicies.some(policy=>(policy.coveredPersonIds||[]).includes('child:'+child.id));if(covered){alert('This child is linked to an insurance policy. Remove the policy relationship before deleting the profile.');return}if(confirm('Delete '+child.firstName+'\'s child profile? The linked Rolodex contact will be archived.')){const contact=state.rolodexContacts.find(item=>item.id===child.rolodexContactId);if(contact)contact.status='archived';state.householdChildren=state.householdChildren.filter(item=>item.id!==child.id);dataProvider.save(state);renderChildrenSettings()}});lucide.createIcons()};

    const enhanceAssetInsurance=()=>{const view=$('#physicalAssetDetailView'),assetId=state.physicalAssetDetailId;if(!view||!assetId)return;view.querySelector('#assetInsuranceCard')?.remove();const policies=state.insurancePolicies.filter(policy=>policy.assetId===assetId&&policy.status!=='Archived');if(!policies.length)return;const card=document.createElement('article');card.id='assetInsuranceCard';card.className='card asset-detail-section';card.innerHTML=`<div class="card-head"><div><h2>Insurance</h2><div class="card-note">Policies attached to this asset.</div></div><button class="link-btn" data-open-page="Insurance">Open Insurance</button></div>${policies.map(policy=>`<div class="asset-linked-row"><div><strong>${esc(policy.policyName)}</strong><p>${esc(policy.company)} · renews ${dateLabel(policy.renewalDate)}</p></div><button class="secondary-btn" data-open-asset-policy="${policy.id}">View</button></div>`).join('')}`;(view.querySelector('.asset-detail-columns')||view).append(card);card.querySelector('[data-open-page]').onclick=()=>setPage('Insurance');$$('[data-open-asset-policy]',card).forEach(button=>button.onclick=()=>openPolicy(button.dataset.openAssetPolicy));lucide.createIcons()};
    const basePhysicalRender=window.renderPhysicalAssets;if(typeof basePhysicalRender==='function')window.renderPhysicalAssets=function(){basePhysicalRender();requestAnimationFrame(enhanceAssetInsurance)};

    CoreValleyModules.register('Insurance',()=>renderInsurance());
    CoreValleyModules.register('Settings',()=>renderChildrenSettings());
    addEventListener('corevalley:mounted',event=>{if(event.detail.page==='Physical Assets')requestAnimationFrame(enhanceAssetInsurance)});
    dataProvider.save(state);lucide.createIcons();
  };
  installInsurance();
})();
