(()=>{
  function installInvestmentTrades(){
    const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
    const today=()=>{const date=new Date(),pad=value=>String(value).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`};
    const activePositions=()=>state.positions.filter(position=>position.status!=='closed');
    const accountName=id=>state.investmentAccounts.find(account=>account.id===id)?.nickname||'Unknown account';
    const currentUserName=()=>state.householdUsers?.find(user=>user.id===state.appSettings?.currentUserId)?.displayName||state.householdUsers?.[0]?.displayName||'Household user';

    document.head.insertAdjacentHTML('beforeend',`<style>
      .investment-trade-actions{display:flex;gap:10px;flex-wrap:wrap}.trade-primary{min-width:112px;justify-content:center;font-size:14px;padding:11px 17px}.trade-sell{background:#fff;border:1px solid var(--brand);color:var(--brand)}
      .trade-tabs{display:flex;gap:7px;padding:5px;background:var(--wash);border-radius:12px;margin:16px 0}.trade-tab{flex:1;border:0;border-radius:9px;background:transparent;padding:10px 12px;font-weight:800;color:var(--muted);cursor:pointer}.trade-tab.active{background:#fff;color:var(--brand);box-shadow:0 2px 9px rgba(25,54,44,.09)}
      .trade-panel[hidden]{display:none}.trade-position-editor{display:grid;grid-template-columns:minmax(150px,1fr) 150px;align-items:center;gap:14px;padding:12px 0;border-bottom:1px solid var(--line)}.trade-position-editor:last-child{border-bottom:0}.trade-position-editor input{text-align:right}.trade-account-heading{font-size:13px;color:var(--brand);font-weight:900;margin:18px 0 3px}.trade-account-heading:first-child{margin-top:0}
      .position-edit-large{min-width:88px;min-height:38px;justify-content:center;font-size:13px}.position-edit-attention{background:#b63a2f!important;border-color:#b63a2f!important;color:#fff!important}.cost-basis-warning{display:inline-flex;align-items:center;gap:5px;color:#a52f24;font-weight:800;font-size:12px;margin-top:4px}.trade-help{padding:11px 13px;border-radius:10px;background:#f3f7f5;color:var(--muted);font-size:13px;line-height:1.45}.trade-new-fields{display:none}.trade-new-fields.visible{display:contents}
      @media(max-width:700px){.trade-position-editor{grid-template-columns:1fr}.trade-position-editor input{text-align:left}}
    </style>`);

    document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="investmentTradeModal"><form class="modal" id="investmentTradeForm"><div class="modal-head"><div><h2 id="investmentTradeTitle">Buy investment</h2><div class="card-note">Record current activity without changing the historical transaction-entry workflow.</div></div><button class="close-btn" type="button" data-close-investment-trade><i data-lucide="x"></i></button></div><div class="trade-tabs"><button class="trade-tab active" type="button" data-trade-tab="individual">Individual trade</button><button class="trade-tab" type="button" data-trade-tab="group">Group share update</button></div><section class="trade-panel" id="individualTradePanel"><div class="form-grid"><div class="field"><label>Action</label><select id="tradeAction"><option>Buy</option><option>Sell</option></select></div><div class="field"><label>Trade date</label><input id="tradeDate" type="date" required></div><div class="field full"><label>Investment account</label><select id="tradeAccount" required></select></div><div class="field full"><label>Position</label><select id="tradePosition" required></select></div><div class="trade-new-fields" id="tradeNewFields"><div class="field"><label>New symbol</label><input id="tradeNewSymbol" maxlength="20"></div><div class="field"><label>Position name</label><input id="tradeNewName"></div><div class="field full"><label>Asset class</label><select id="tradeNewAssetClass"><option>US Stock</option><option>International Stock</option><option>ETF</option><option>Bond</option><option>Mutual Fund</option><option>Crypto</option><option>Other</option></select></div></div><div class="field"><label>Shares / units</label><input id="tradeShares" type="number" min=".000001" step=".000001" required></div><div class="field"><label>Purchase / sale price <span class="sub">(optional)</span></label><input id="tradePrice" type="number" min="0" step=".000001"></div><div class="field"><label>Fees</label><input id="tradeFee" type="number" min="0" step=".01" value="0"></div><div class="field full"><div class="trade-help">If a Buy price is omitted, CoreValley will flag the position and create a task to update its cost basis. Sell prices may also be left blank.</div></div></div></section><section class="trade-panel" id="groupTradePanel" hidden><div class="form-grid"><div class="field"><label>Adjustment date</label><input id="groupTradeDate" type="date" required></div><div class="field full"><div class="trade-help">Enter the current share count for any positions that changed. Each change creates a dated adjustment showing the old count, new count, and difference.</div></div></div><div id="groupShareRows"></div></section><div class="modal-foot"><div class="modal-actions"><button class="secondary-btn" type="button" data-close-investment-trade>Cancel</button><button class="primary-btn" type="submit" id="saveInvestmentTrade">Record buy</button></div></div></form></div>`);

    const modal=$('#investmentTradeModal'),form=$('#investmentTradeForm');
    const closeTrade=()=>modal.classList.remove('open');
    const setTab=tab=>{$$('[data-trade-tab]').forEach(button=>button.classList.toggle('active',button.dataset.tradeTab===tab));$('#individualTradePanel').hidden=tab!=='individual';$('#groupTradePanel').hidden=tab!=='group';$$('#individualTradePanel input,#individualTradePanel select').forEach(control=>control.disabled=tab!=='individual');$$('#groupTradePanel input,#groupTradePanel select').forEach(control=>control.disabled=tab!=='group');$('#saveInvestmentTrade').textContent=tab==='group'?'Save share updates':'Record '+$('#tradeAction').value.toLowerCase();form.dataset.tab=tab};
    const fillAccounts=()=>{$('#tradeAccount').innerHTML=state.investmentAccounts.map(account=>`<option value="${account.id}">${esc(account.nickname)} · ${esc(account.owner)}</option>`).join('')};
    const fillPositions=()=>{const action=$('#tradeAction').value,rows=activePositions().filter(position=>position.accountId===$('#tradeAccount').value);$('#tradePosition').innerHTML=(action==='Buy'?'<option value="new">+ Add a new position</option>':'')+rows.map(position=>`<option value="${position.id}">${esc(position.symbol||position.name)} · ${Number(position.shares).toLocaleString('en-US',{maximumFractionDigits:6})} shares</option>`).join('');if(!rows.length&&action==='Sell')$('#tradePosition').innerHTML='<option value="">No active positions in this account</option>';syncNewFields()};
    const syncNewFields=()=>{const isNew=$('#tradePosition').value==='new'&&$('#tradeAction').value==='Buy';$('#tradeNewFields').classList.toggle('visible',isNew);$('#tradeNewSymbol').required=isNew;$('#tradeNewName').required=isNew};
    const renderGroupRows=()=>{const grouped=new Map();activePositions().forEach(position=>{if(!grouped.has(position.accountId))grouped.set(position.accountId,[]);grouped.get(position.accountId).push(position)});$('#groupShareRows').innerHTML=[...grouped].map(([accountId,positions])=>`<div class="trade-account-heading">${esc(accountName(accountId))}</div>${positions.map(position=>`<label class="trade-position-editor"><span><strong>${esc(position.symbol||position.name)}</strong><span class="sub" style="display:block">${esc(position.name)} · current ${Number(position.shares).toLocaleString('en-US',{maximumFractionDigits:6})}</span></span><input type="number" min="0" step=".000001" value="${Number(position.shares).toFixed(6)}" data-group-position="${position.id}" aria-label="Updated shares for ${esc(position.symbol||position.name)}"></label>`).join('')}`).join('')||'<div class="sub">No active positions are available.</div>'};
    const openTrade=action=>{form.reset();form.dataset.tab='individual';$('#tradeAction').value=action;$('#tradeDate').value=today();$('#groupTradeDate').value=today();$('#tradeFee').value='0';fillAccounts();fillPositions();renderGroupRows();$('#investmentTradeTitle').textContent=action+' investments';setTab('individual');modal.classList.add('open');lucide.createIcons()};
    const createBasisTask=position=>{state.householdTasks=state.householdTasks||[];const existing=state.householdTasks.some(task=>task.status!=='completed'&&task.relatedPositionId===position.id&&task.taskKind==='costBasisUpdate');if(existing)return;state.householdTasks.push({id:'task-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),title:'Update cost basis for '+(position.symbol||position.name),category:'Financial',recurrence:'One-time',dueDate:'',createdBy:currentUserName(),claimedBy:'',requestNotes:'A Buy transaction was recorded without a purchase price. Update the position cost basis when the brokerage information is available.',status:'open',taskKind:'costBasisUpdate',relatedPositionId:position.id})};
    const refreshInvestments=()=>{renderInvestments();renderInvestmentEnhancements();renderRsusV2();refreshRsuInvestmentTotal()};
    const recordIndividualTrade=()=>{const action=$('#tradeAction').value,shares=Number($('#tradeShares').value),priceText=$('#tradePrice').value.trim(),hasPrice=priceText!=='',price=hasPrice?Number(priceText):0,fee=Number($('#tradeFee').value)||0,date=$('#tradeDate').value,accountId=$('#tradeAccount').value;if(!shares||shares<=0)return showToast('Enter a share quantity greater than zero.');let position=$('#tradePosition').value==='new'?null:state.positions.find(item=>item.id===$('#tradePosition').value);if(action==='Sell'&&!position)return showToast('Select an active position to sell.');if(action==='Sell'&&shares>Number(position.shares)+0.0000001)return showToast('The sale cannot exceed the shares currently held.');if(!position){const symbol=$('#tradeNewSymbol').value.trim().toUpperCase(),name=$('#tradeNewName').value.trim();position={id:'pos-'+Date.now(),accountId,assetClass:$('#tradeNewAssetClass').value,symbol,name,shares:0,costBasisPerShare:0,currentPrice:hasPrice?price:0,priceDate:date,priceSource:'Manual',dividendPerShare:0,dividendFrequency:'none',notes:'',status:'active'};state.positions.push(position)}const oldShares=Number(position.shares)||0,oldBasis=Number(position.costBasisPerShare)||0,newShares=action==='Buy'?oldShares+shares:Math.max(0,oldShares-shares);if(action==='Buy'&&hasPrice&&newShares>0){position.costBasisPerShare=(oldShares*oldBasis+shares*price+fee)/newShares;position.costBasisNeedsUpdate=false}else if(action==='Buy'&&!hasPrice){position.costBasisNeedsUpdate=true;createBasisTask(position)}if(hasPrice){position.currentPrice=price;position.priceDate=date}position.shares=Number(newShares.toFixed(6));position.accountId=accountId;if(position.shares===0){position.status='closed';position.closedDate=date;position.closeReason='Fully sold'}state.investmentTransactions.push({id:'tx-'+Date.now(),accountId,date,type:action,symbol:position.symbol||position.name,positionId:position.id,shares,price:hasPrice?price:null,priceMissing:!hasPrice,fee,costBasis:position.costBasisPerShare,previousShares:oldShares,newShares:position.shares});dataProvider.save(state);closeTrade();refreshInvestments();if(typeof renderTasks==='function')renderTasks();showToast(action+' recorded for '+(position.symbol||position.name)+(position.status==='closed'?'; position archived.':'.'))};
    const recordGroupUpdates=()=>{const date=$('#groupTradeDate').value;let count=0;$$('[data-group-position]').forEach(input=>{const position=state.positions.find(item=>item.id===input.dataset.groupPosition);if(!position)return;const oldShares=Number(position.shares)||0,newShares=Number(Number(input.value||0).toFixed(6));if(Math.abs(oldShares-newShares)<0.0000005)return;position.shares=newShares;if(newShares===0){position.status='closed';position.closedDate=date;position.closeReason='Share-count update reached zero'}state.investmentTransactions.push({id:'tx-'+Date.now()+'-'+count,accountId:position.accountId,date,type:'Share adjustment',symbol:position.symbol||position.name,positionId:position.id,shares:newShares-oldShares,price:null,priceMissing:true,fee:0,costBasis:position.costBasisPerShare,previousShares:oldShares,newShares});count++});if(!count)return showToast('No share counts changed.');dataProvider.save(state);closeTrade();refreshInvestments();showToast(count+' share count '+(count===1?'update':'updates')+' saved.')};

    form.onsubmit=event=>{event.preventDefault();form.dataset.tab==='group'?recordGroupUpdates():recordIndividualTrade()};
    $$('[data-close-investment-trade]').forEach(button=>button.onclick=closeTrade);
    $$('[data-trade-tab]').forEach(button=>button.onclick=()=>setTab(button.dataset.tradeTab));
    $('#tradeAction').onchange=()=>{fillPositions();$('#investmentTradeTitle').textContent=$('#tradeAction').value+' investments';setTab('individual')};
    $('#tradeAccount').onchange=fillPositions;$('#tradePosition').onchange=syncNewFields;

    const baseRenderInvestmentsTrades=renderInvestments;
    renderInvestments=function(){baseRenderInvestmentsTrades();const intro=$('#investmentsPage .module-intro .report-actions');if(intro&&!$('#buyInvestmentBtn'))intro.insertAdjacentHTML('afterbegin','<div class="investment-trade-actions"><button class="primary-btn trade-primary" id="buyInvestmentBtn"><i data-lucide="trending-up"></i>Buy</button><button class="primary-btn trade-primary trade-sell" id="sellInvestmentBtn"><i data-lucide="trending-down"></i>Sell</button></div>');$('#buyInvestmentBtn').onclick=()=>openTrade('Buy');$('#sellInvestmentBtn').onclick=()=>openTrade('Sell');$$('[data-card-add-position],[data-account-position]').forEach(button=>button.remove());const accounts=visibleInvestmentAccounts(),ids=new Set(accounts.map(account=>account.id)),visible=activePositions().filter(position=>ids.has(position.accountId));$$('#positionsBody tr').forEach((row,index)=>{const position=visible[index];if(!position)return;const cell=row.lastElementChild,edit=cell?.querySelector('[data-edit-position]');if(edit){edit.classList.add('position-edit-large');edit.textContent='Edit details';if(position.costBasisNeedsUpdate){edit.classList.add('position-edit-attention');edit.title='Purchase price missing — update cost basis';row.children[0]?.insertAdjacentHTML('beforeend','<span class="cost-basis-warning"><i data-lucide="triangle-alert"></i>Cost basis needs update</span>')}}});lucide.createIcons()};

    const baseRenderInvestmentHistoryTrades=renderInvestmentEnhancements;
    renderInvestmentEnhancements=function(){baseRenderInvestmentHistoryTrades();$$('[data-card-add-position],[data-account-position]').forEach(button=>button.remove());const filter=state.transactionAccountFilter||'all',transactions=state.investmentTransactions.filter(item=>filter==='all'||item.accountId===filter).slice().sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#investmentTransactions').innerHTML=transactions.map(item=>{const adjustment=item.type==='Share adjustment',quantity=adjustment?`${Number(item.previousShares).toLocaleString('en-US',{maximumFractionDigits:6})} → ${Number(item.newShares).toLocaleString('en-US',{maximumFractionDigits:6})} (${Number(item.shares)>=0?'+':''}${Number(item.shares).toLocaleString('en-US',{maximumFractionDigits:6})})`:`${Number(item.shares).toLocaleString('en-US',{maximumFractionDigits:6})} @ ${item.priceMissing||item.price===null?'price not entered':money(item.price)}`,gross=Number(item.shares)*Number(item.price),total=item.priceMissing||item.price===null?'—':money(item.type==='Sell'?gross-Number(item.fee||0):gross+Number(item.fee||0));return `<div class="transaction-row"><span>${new Date(item.date+'T12:00').toLocaleDateString('en-US')}</span><span><strong>${esc(item.type)} ${esc(item.symbol)}</strong><br><span class="sub">${esc(accountName(item.accountId))} · ${quantity}${adjustment?'':' · Fee '+money(item.fee||0)}</span></span><strong>${total}</strong></div>`}).join('')||'<div class="sub" style="padding:12px">No transactions.</div>'};

    CoreValleyModules.register('Investments',()=>{renderInvestments();renderInvestmentEnhancements();renderRsusV2();refreshRsuInvestmentTotal()});
  }
  installInvestmentTrades();
})();
