  function installInvestmentCardCorrection(){
    document.head.insertAdjacentHTML('beforeend',`<style>.investment-badge-center{display:inline-flex!important;align-items:center!important;justify-content:center!important;text-align:center!important;min-width:86px;min-height:28px;line-height:1.15;padding:5px 10px}.account-add-position{flex:1;justify-content:center;min-width:135px}.private-entry-note{margin-top:8px;padding:10px 12px;background:#eef7f3;border:1px solid #cfe5da;border-radius:10px;color:#315b4d;font-size:10px;line-height:1.5}.private-entry-note strong{display:block;font-size:11px;margin-bottom:2px}.unlisted-status{display:inline-flex;align-items:center;gap:6px;background:#fff1cc;color:#725315;border-radius:20px;padding:6px 10px;font-size:10px;font-weight:800;margin-bottom:10px}</style>`);
    if(!state.positions.some(p=>p.id==='pos-demo-cash'))state.positions.push({id:'pos-demo-cash',accountId:'inv-schwab',symbol:'Schwab Government Money Fund',identifier:'Schwab Government Money Fund',name:'Schwab Government Money Fund',assetClass:'Cash',shares:12500,costBasisPerShare:1,currentPrice:1,priceDate:'2026-08-08',priceSource:'Manual cash balance — APY',apy:4.35,isCashEquivalent:true,dividendPerShare:0,dividendFrequency:'none',notes:'Uninvested brokerage cash swept to money market'});
    if(!$('#cashPositionFields'))$('#privatePositionFields').insertAdjacentHTML('afterend','<div class="field full" id="cashPositionFields" style="display:none"><div class="unlisted-status">Cash / uninvested cash / money market</div><div class="form-grid"><div class="field"><label>Annual percentage yield (APY)</label><input id="positionCashApy" type="number" min="0" step=".001"></div></div><div class="private-entry-note"><strong>Interest-bearing cash holding</strong>Use Name for a flexible label such as uninvested cash or a money market fund. Projected income uses balance × APY; dividend-per-share inputs do not apply.</div></div>');
    const basePositionIncome=positionIncome;positionIncome=function(p){return p.assetClass==='Cash'||p.isCashEquivalent?positionValue(p)*Number(p.apy||0)/100:basePositionIncome(p)};
    const baseOpenPositionModal=openPositionModal;
    const privateOption=$$('#positionAssetClass option').find(o=>o.value==='Private Company');if(privateOption){privateOption.textContent='Private Company / Unlisted';privateOption.value='Private Company'}
    const syncPrivatePositionFields=()=>{const isPrivate=$('#positionAssetClass').value==='Private Company',isCash=$('#positionAssetClass').value==='Cash',noTicker=isPrivate||isCash;$('#privatePositionFields').style.display=isPrivate?'block':'none';$('#cashPositionFields').style.display=isCash?'block':'none';$('#positionSymbol').required=!noTicker;$('#positionSymbol').disabled=noTicker;$('#positionPrice').required=!noTicker;$('#positionPrice').disabled=noTicker;$('#positionPriceDate').required=!noTicker;$('#positionPriceDate').disabled=noTicker;$('#positionSymbol').closest('.field').style.display=noTicker?'none':'grid';$('#positionPrice').closest('.field').style.display=noTicker?'none':'grid';$('#positionPriceDate').closest('.field').style.display=noTicker?'none':'grid';$('#positionDividend').closest('.field').style.display=noTicker?'none':'grid';$('#positionFrequency').closest('.field').style.display=noTicker?'none':'grid';$('#positionModalTitle').textContent=isPrivate?($('#positionId').value?'Edit unlisted company position':'New unlisted company position'):isCash?($('#positionId').value?'Edit cash or money-market holding':'New cash or money-market holding'):($('#positionId').value?'Edit position':'New position')};
    openPositionModal=function(id,accountId){baseOpenPositionModal(id);const p=id?state.positions.find(x=>x.id===id):null;if(accountId)$('#positionAccount').value=accountId;if(p?.isPrivate||p?.assetClass==='Private Company'){$('#positionAssetClass').value='Private Company';$('#positionEstimatedValue').value=p.estimatedValue||'';$('#positionValuationDate').value=p.valuationDate||p.priceDate||'';$('#positionValuationConfidence').value=p.valuationConfidence||'Owner estimate'}if(p?.assetClass==='Cash'||p?.isCashEquivalent){$('#positionAssetClass').value='Cash';$('#positionCashApy').value=p.apy||''}syncPrivatePositionFields()};
    $('#positionAssetClass').onchange=syncPrivatePositionFields;
    if(!$('#privatePositionFields .private-entry-note'))$('#privatePositionFields').insertAdjacentHTML('afterbegin','<div class="unlisted-status">Unlisted / non-traded equity</div><div class="private-entry-note"><strong>Automated price lookup disabled</strong>The company name is the holding identifier. Enter units or shares, cost basis, a dated estimated valuation, confidence/appraisal status, and notes. No ticker symbol or market quote is stored or requested.</div>');
    const privateAwareSubmit=$('#positionForm').onsubmit;$('#positionForm').onsubmit=e=>{const editing=$('#positionId').value,isPrivate=$('#positionAssetClass').value==='Private Company',isCash=$('#positionAssetClass').value==='Cash';if(isPrivate||isCash){$('#positionSymbol').value=$('#positionName').value.trim();if(isCash){$('#positionPrice').value=1;$('#positionPriceDate').value=new Date().toISOString().slice(0,10)}}privateAwareSubmit(e);const saved=editing?state.positions.find(p=>p.id===editing):state.positions.at(-1);if(saved&&isPrivate){saved.symbol=saved.name;saved.identifier=saved.name;saved.isListed=false;saved.isCashEquivalent=false;saved.priceSource='Private valuation — no automated lookup';dataProvider.save(state)}else if(saved&&isCash){saved.symbol=saved.name;saved.identifier=saved.name;saved.isListed=false;saved.isCashEquivalent=true;saved.apy=Number($('#positionCashApy').value)||0;saved.currentPrice=1;saved.dividendPerShare=0;saved.dividendFrequency='none';saved.priceSource='Manual cash balance — APY';dataProvider.save(state)}else if(saved){saved.isListed=true;saved.isCashEquivalent=false;saved.identifier=saved.symbol}renderInvestments();renderInvestmentEnhancements()};
    const baseEnhanceInvestments=renderInvestmentEnhancements;
    renderInvestmentEnhancements=function(){baseEnhanceInvestments();$$('#investmentAccountList .inventory-actions').forEach(actions=>{if(actions.querySelector('[data-card-add-position]'))actions.querySelectorAll('[data-account-position]').forEach(b=>b.remove())})};
    const baseRenderInvestments=renderInvestments;
    renderInvestments=function(){const allPositions=state.positions,activePositions=allPositions.filter(p=>p.status!=='closed');state.positions=activePositions;baseRenderInvestments();state.positions=allPositions;const accounts=visibleInvestmentAccounts(),cards=$$('#investmentAccountList > article.card');cards.forEach((card,i)=>{const account=accounts[i],actions=card.querySelector('.inventory-actions'),badge=card.querySelector('.inventory-badge');if(badge)badge.classList.add('investment-badge-center');if(account&&actions&&!actions.querySelector('[data-card-add-position]'))actions.insertAdjacentHTML('afterbegin','<button class="primary-btn account-add-position" data-card-add-position="'+account.id+'"><i data-lucide="plus"></i>Add Position</button>')});const visibleIds=new Set(accounts.map(a=>a.id)),visibleActive=activePositions.filter(p=>visibleIds.has(p.accountId));$$('#positionsBody tr').forEach((row,i)=>{const p=visibleActive[i];if(!p)return;if(p.isPrivate||p.assetClass==='Private Company'){row.children[0].innerHTML='<span class="symbol">'+p.name+'</span><br><span class="sub">Unlisted / non-traded · no automated lookup</span>';row.children[3].innerHTML=money(positionValue(p)/Math.max(1,Number(p.shares)))+'<br><span class="sub">Private valuation · '+(p.valuationDate||p.priceDate)+'</span>'}if(p.assetClass==='Cash'||p.isCashEquivalent){row.children[0].innerHTML='<span class="symbol">'+p.name+'</span><br><span class="sub">Cash / money market · APY income</span>';row.children[3].innerHTML=money(1)+'<br><span class="sub">Cash balance unit · manual</span>';row.children[6]?.insertAdjacentHTML('beforeend','<br><span class="sub">'+money(positionIncome(p)/12)+' monthly · '+Number(p.apy||0).toFixed(3)+'% APY</span>')}});$$('[data-card-add-position]').forEach(b=>b.onclick=()=>openPositionModal(null,b.dataset.cardAddPosition));lucide.createIcons()};
  }
  installInvestmentCardCorrection();
  function installFractionalRsuSupport(){
    const formatRsuShares=value=>Number(value||0).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:6});
    document.head.insertAdjacentHTML('beforeend','<style>.rsu-precision-note{font-size:10px;color:var(--muted);margin:7px 0 10px}.rsu-edit-actions{display:flex;justify-content:flex-end;margin-top:12px}</style>');
    if(!$('#rsuId'))$('#rsuForm').insertAdjacentHTML('afterbegin','<input type="hidden" id="rsuId">');
    const vestLabel=$('#vestingEventRows').parentElement.querySelector('label');if(vestLabel&&!$('#rsuPrecisionNote'))vestLabel.insertAdjacentHTML('afterend','<div class="rsu-precision-note" id="rsuPrecisionNote">Fractional vesting shares are supported to 6 decimal places.</div>');
    const baseAddDynamicRow=addDynamicRow;addDynamicRow=function(containerId,a='',b='',kind='vest'){baseAddDynamicRow(containerId,a,b,kind);if(kind==='vest'){const input=$('#'+containerId).lastElementChild?.querySelector('.vest-shares');if(input){input.step='.000001';input.inputMode='decimal';input.min='0'}}};
    const openRsuEditor=id=>{const g=id?state.rsuGrants.find(x=>x.id===id):null;$('#rsuForm').reset();$('#rsuId').value=g?.id||'';$('#rsuForm .modal-head h2').textContent=g?'Edit RSU grant':'New RSU grant';$('#rsuGrantDate').value=g?.grantDate||new Date().toISOString().slice(0,10);$('#vestingEventRows').innerHTML='';$('#tradingWindowRows').innerHTML='';if(g){$('#rsuOwner').value=g.owner;$('#rsuEmployer').value=g.employer;$('#rsuSymbol').value=g.symbol;$('#rsuGrantId').value=g.grantId;$('#rsuPrice').value=g.currentPrice;(g.vestingEvents||[]).forEach(v=>addDynamicRow('vestingEventRows',v.date,formatRsuShares(v.shares),'vest'));(state.tradingWindows[g.symbol]||[]).forEach(w=>addDynamicRow('tradingWindowRows',w.start,w.end,'window'))}else addDynamicRow('vestingEventRows',new Date(new Date().setMonth(new Date().getMonth()+3)).toISOString().slice(0,10),'','vest');$('#rsuModal').classList.add('open')};
    $('#newRsuBtn').onclick=()=>openRsuEditor();
    $('#rsuForm').onsubmit=e=>{e.preventDefault();const id=$('#rsuId').value||'rsu-'+Date.now(),symbol=$('#rsuSymbol').value.trim().toUpperCase(),vestingEvents=$$('.dynamic-row').filter(r=>r.closest('#vestingEventRows')).map(r=>({date:r.querySelector('.vest-date').value,shares:Number(r.querySelector('.vest-shares').value)})),windows=$$('.dynamic-row').filter(r=>r.closest('#tradingWindowRows')).map(r=>({start:r.querySelector('.window-start').value,end:r.querySelector('.window-end').value})),item={id,owner:$('#rsuOwner').value,employer:$('#rsuEmployer').value.trim(),symbol,grantId:$('#rsuGrantId').value.trim(),grantDate:$('#rsuGrantDate').value,currentPrice:Number($('#rsuPrice').value),vestingEvents},existing=state.rsuGrants.find(g=>g.id===id);state.rsuGrants.filter(g=>g.symbol===symbol).forEach(g=>g.currentPrice=item.currentPrice);if(existing)Object.assign(existing,item);else state.rsuGrants.push(item);state.tradingWindows[symbol]=windows;dataProvider.save(state);$('#rsuModal').classList.remove('open');renderInvestments();renderRsusV2();renderRsuDashboard();refreshRsuInvestmentTotal();showToast('RSU grant saved with '+formatRsuShares(vestingEvents.reduce((n,v)=>n+v.shares,0))+' total shares.')};
    const baseRenderRsus=renderRsusV2;renderRsusV2=function(){baseRenderRsus();const filters=state.investmentFilters||{owner:'all'},grants=(state.rsuGrants||[]).filter(g=>filters.owner==='all'||g.owner===filters.owner),cards=$$('#rsuList > article.card');cards.forEach((card,i)=>{const g=grants[i],s=g?rsuStats(g):null;if(!g||!s)return;const breakdown=card.querySelector('.account-breakdown');if(breakdown)breakdown.innerHTML='<span class="breakdown-pill">Vested '+formatRsuShares(s.vested)+' · '+money(s.vested*g.currentPrice)+'</span><span class="breakdown-pill">Unvested '+formatRsuShares(s.unvested)+' · '+money(s.unvested*g.currentPrice)+'</span>';const equity=card.querySelector('.equity-line span');if(equity)equity.textContent=s.next?'Next: '+formatRsuShares(s.next.shares)+' shares on '+new Date(s.next.date+'T12:00').toLocaleDateString('en-US'):'Fully vested';if(!card.querySelector('[data-edit-rsu]'))card.insertAdjacentHTML('beforeend','<div class="rsu-edit-actions"><button class="secondary-btn" data-edit-rsu="'+g.id+'">Edit grant</button></div>')});$$('[data-edit-rsu]').forEach(b=>b.onclick=()=>openRsuEditor(b.dataset.editRsu));lucide.createIcons()};
  }
  installFractionalRsuSupport();
