  function installRecurringHouseholdPages(){
    document.head.insertAdjacentHTML('beforeend',`<style>.recurring-page{display:none}.recurring-page.active{display:block}.recurring-summary{grid-template-columns:repeat(4,1fr);margin-bottom:16px}.recurring-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.recurring-card{position:relative}.recurring-icon{width:40px;height:40px;border-radius:12px;background:var(--mint);color:var(--brand-2);display:grid;place-items:center}.recurring-amount{font:800 23px Manrope;margin:15px 0 4px}.recurring-meta{display:grid;gap:7px;margin:14px 0}.recurring-meta-row{display:flex;justify-content:space-between;gap:10px;font-size:10px}.autopay-on{background:var(--mint);color:var(--brand-2)}.autopay-off{background:#f2f3f2;color:var(--muted)}.upcoming-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.upcoming-charge{background:#f7f9f8;border-radius:11px;padding:10px}.giving-layout{display:grid;grid-template-columns:1fr 1fr;gap:16px}.giving-entry{display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:start;padding:11px 0;border-bottom:1px solid var(--line)}.giving-entry:last-child{border-bottom:0}.giving-kind{width:42px;height:42px;border-radius:12px;background:#fff4d8;color:#7a5715;display:grid;place-items:center}.receipt-link{font-size:9px;font-weight:700;color:var(--brand-2)}@media(max-width:1000px){.recurring-grid{grid-template-columns:1fr 1fr}.upcoming-strip{grid-template-columns:1fr 1fr}}@media(max-width:760px){.recurring-summary,.recurring-grid,.giving-layout,.upcoming-strip{grid-template-columns:1fr}}</style>`);
    document.head.insertAdjacentHTML('beforeend','<style>.recurring-logo{width:44px;height:44px;border-radius:12px;background:#f3f6f4;border:1px solid var(--line);display:grid;place-items:center;overflow:hidden;color:var(--muted);font-size:8px;font-weight:700;text-align:center}.recurring-logo img{width:100%;height:100%;object-fit:contain;background:#fff}.utility-service-icon{width:44px;height:44px;border-radius:12px;background:var(--mint);color:var(--brand-2);display:grid;place-items:center}.utility-service-icon i{width:21px}</style>');
    const utilitiesButton=$('.nav button[data-page="Utilities"]');if(utilitiesButton&&!$('.nav button[data-page="Charitable Donations"]'))utilitiesButton.insertAdjacentHTML('afterend','<button data-page="Charitable Donations" data-icon="heart-handshake"><i data-lucide="heart-handshake"></i>Charitable Donations</button>');
    const makePage=(id,title,copy,buttonLabel)=>{const section=document.createElement('section');section.className='recurring-page';section.id=id;section.innerHTML=`<div class="module-intro"><div><h2 style="font-size:20px">${title}</h2><div class="module-copy">${copy}</div></div><button class="primary-btn" data-recurring-new><i data-lucide="plus"></i>${buttonLabel}</button></div><div class="grid recurring-summary"><article class="card"><div class="kpi-label">Monthly equivalent</div><div class="inventory-value" data-monthly-total>$0</div></article><article class="card"><div class="kpi-label">Annual commitment</div><div class="inventory-value" data-annual-total>$0</div></article><article class="card"><div class="kpi-label">Active records</div><div class="inventory-value" data-active-count>0</div></article><article class="card"><div class="kpi-label">Autopay enabled</div><div class="inventory-value" data-autopay-count>0</div></article></div><article class="card"><div class="card-head"><div><h2>Upcoming charges</h2><div class="card-note">Next scheduled charges across the visible category.</div></div></div><div class="upcoming-strip" data-upcoming></div></article><div class="recurring-grid section-gap" data-recurring-list></div>`;$('#placeholder').before(section);return section};
    const subscriptionsPage=makePage('subscriptionsPage','Subscriptions','Optional and discretionary recurring services such as streaming, software, and memberships.','New subscription');
    const utilitiesPage=makePage('utilitiesPage','Utilities','Essential household services including electricity, solar, water, garbage, phone, and internet.','New utility');
    const donationsPage=document.createElement('section');donationsPage.className='recurring-page';donationsPage.id='donationsPage';donationsPage.innerHTML=`<div class="module-intro"><div><h2 style="font-size:20px">Charitable Donations</h2><div class="module-copy">Personal giving records for recurring, one-time cash, and in-kind donations. Tax calculations and tax reporting are intentionally excluded.</div></div><div class="report-actions"><button class="secondary-btn" id="newRecurringDonationBtn">New recurring gift</button><button class="primary-btn" id="newDonationEntryBtn"><i data-lucide="plus"></i>Record one-time gift</button></div></div><div class="grid recurring-summary"><article class="card"><div class="kpi-label">Year-to-date giving</div><div class="inventory-value" id="givingYtd">$0</div></article><article class="card"><div class="kpi-label">Cash giving YTD</div><div class="inventory-value" id="givingCashYtd">$0</div></article><article class="card"><div class="kpi-label">In-kind value YTD</div><div class="inventory-value" id="givingInKindYtd">$0</div></article><article class="card"><div class="kpi-label">Recurring monthly</div><div class="inventory-value" id="givingRecurringMonthly">$0</div></article></div><article class="card"><div class="card-head"><div><h2>Recurring giving</h2><div class="card-note">Ongoing commitments with next date, payment account, and organization link.</div></div></div><div class="recurring-grid" id="recurringGivingList"></div></article><div class="giving-layout section-gap"><article class="card"><div class="card-head"><div><h2>One-time cash gifts</h2><div class="card-note">Occasional gifts and acknowledgments.</div></div><button class="secondary-btn" data-gift-kind="cash">Add cash gift</button></div><div id="cashGivingList"></div></article><article class="card"><div class="card-head"><div><h2>In-kind donations</h2><div class="card-note">Description, organization, date, estimated value, and optional receipt link.</div></div><button class="secondary-btn" data-gift-kind="in-kind">Add in-kind gift</button></div><div id="inKindGivingList"></div></article></div>`;$('#placeholder').before(donationsPage);
    state.recurringItems=state.recurringItems||[
      {id:'sub-netflix',type:'subscription',name:'Netflix',provider:'Netflix',amount:24.99,frequency:'monthly',nextDueDate:'2026-08-18',paymentAccountId:'card-amex',autopay:true,serviceUrl:'https://www.netflix.com/account'},
      {id:'sub-gym',type:'subscription',name:'Family gym membership',provider:'Anytime Fitness',amount:69,frequency:'monthly',nextDueDate:'2026-09-01',paymentAccountId:'card-chase',autopay:true,serviceUrl:'https://www.anytimefitness.com/'},
      {id:'sub-cloud',type:'subscription',name:'Cloud storage',provider:'Google One',amount:99.99,frequency:'annual',nextDueDate:'2026-11-12',paymentAccountId:'card-costco',autopay:true,serviceUrl:'https://one.google.com/'},
      {id:'util-electric',type:'utility',name:'Electricity',provider:'Duke Energy',amount:184.32,frequency:'monthly',nextDueDate:'2026-08-22',paymentAccountId:'bank-checking',autopay:true,serviceUrl:'https://www.duke-energy.com/'},
      {id:'util-solar',type:'utility',name:'Solar utility',provider:'Sunrun',amount:118.50,frequency:'monthly',nextDueDate:'2026-08-25',paymentAccountId:'bank-checking',autopay:true,serviceUrl:'https://www.sunrun.com/'},
      {id:'util-water',type:'utility',name:'Water & sewer',provider:'County Utilities',amount:92,frequency:'monthly',nextDueDate:'2026-09-05',paymentAccountId:'bank-checking',autopay:false,serviceUrl:'https://www.usa.gov/water-department'},
      {id:'util-garbage',type:'utility',name:'Garbage & recycling',provider:'Waste Management',amount:78,frequency:'quarterly',nextDueDate:'2026-10-01',paymentAccountId:'card-costco',autopay:true,serviceUrl:'https://www.wm.com/'},
      {id:'util-phone',type:'utility',name:'Mobile phones',provider:'T-Mobile',amount:142,frequency:'monthly',nextDueDate:'2026-08-20',paymentAccountId:'card-chase',autopay:true,serviceUrl:'https://www.t-mobile.com/'},
      {id:'util-internet',type:'utility',name:'Home internet',provider:'AT&T Fiber',amount:85,frequency:'monthly',nextDueDate:'2026-08-28',paymentAccountId:'card-amex',autopay:true,serviceUrl:'https://www.att.com/internet/'},
      {id:'gift-church',type:'donation',name:'Church giving',provider:'Valley Community Church',amount:250,frequency:'monthly',nextDueDate:'2026-09-01',paymentAccountId:'bank-checking',autopay:true,serviceUrl:'https://www.example.org/'},
      {id:'gift-compassion',type:'donation',name:'Child sponsorship',provider:'Compassion International',amount:43,frequency:'monthly',nextDueDate:'2026-08-15',paymentAccountId:'card-chase',autopay:true,serviceUrl:'https://www.compassion.com/'}
    ];
    const demoLogos={'sub-netflix':'https://logo.clearbit.com/netflix.com','sub-cloud':'https://logo.clearbit.com/google.com','gift-compassion':'https://logo.clearbit.com/compassion.com'};state.recurringItems.forEach(x=>{if(demoLogos[x.id]&&!x.logoUrl)x.logoUrl=demoLogos[x.id];if(x.paymentAccountId==='bank-checking')x.paymentAccountId='acct-checking'});
    state.donationEntries=state.donationEntries||[
      {id:'de-1',kind:'recurring',organization:'Valley Community Church',date:'2026-07-01',amount:250,description:'Monthly church giving',recurringId:'gift-church',receiptUrl:'https://www.example.org/'},
      {id:'de-2',kind:'recurring',organization:'Compassion International',date:'2026-07-15',amount:43,description:'Monthly child sponsorship',recurringId:'gift-compassion',receiptUrl:'https://www.compassion.com/'},
      {id:'de-3',kind:'cash',organization:'Local Food Bank',date:'2026-05-10',amount:300,description:'Spring food drive gift',receiptUrl:'https://www.feedingamerica.org/'},
      {id:'de-4',kind:'cash',organization:'Habitat for Humanity',date:'2026-06-22',amount:175,description:'Community build contribution',receiptUrl:'https://www.habitat.org/'},
      {id:'de-5',kind:'in-kind',organization:'Goodwill',date:'2026-04-18',amount:480,description:'Clothing, books, and household goods',receiptUrl:'https://www.goodwill.org/'}
    ];
    if(state.inventedChurchDemoRemoved&&!state.churchDemoRestoredAfterCorrection){if(!state.recurringItems.some(item=>item.id==='gift-church'))state.recurringItems.push({id:'gift-church',type:'donation',name:'Church giving',provider:'Valley Community Church',amount:250,frequency:'monthly',nextDueDate:'2026-09-01',paymentAccountId:'acct-checking',autopay:true,serviceUrl:'https://www.example.org/'});if(!state.donationEntries.some(entry=>entry.id==='de-1'))state.donationEntries.push({id:'de-1',kind:'recurring',organization:'Valley Community Church',date:'2026-07-01',amount:250,description:'Monthly church giving',recurringId:'gift-church',receiptUrl:'https://www.example.org/'});state.churchDemoRestoredAfterCorrection=true}
    const frequencyMultiplier={weekly:52,biweekly:26,monthly:12,quarterly:4,semiannual:2,annual:1},monthlyValue=item=>Number(item.amount)*frequencyMultiplier[item.frequency]/12,annualValue=item=>Number(item.amount)*frequencyMultiplier[item.frequency],accountName=id=>state.accounts.find(a=>a.id===id)?.nickname||'Payment account not found',frequencyOptions=selected=>['weekly','biweekly','monthly','quarterly','semiannual','annual'].map(x=>'<option value="'+x+'" '+(x===selected?'selected':'')+'>'+x[0].toUpperCase()+x.slice(1)+'</option>').join(''),accountOptions=selected=>state.accounts.map(a=>'<option value="'+a.id+'" '+(a.id===selected?'selected':'')+'>'+a.nickname+' · '+a.institution+'</option>').join('');
    const openRecurringEditor=(type,id)=>{const item=id?state.recurringItems.find(x=>x.id===id):null,label=type==='subscription'?'subscription':type==='utility'?'utility':'recurring gift';openSimpleData(item?'Edit '+label:'New '+label,'Recurring records keep category, frequency, due date, payment source, autopay, and service/cancellation link explicit.',`<div class="field"><label>Name</label><input id="riName" value="${item?.name||''}" required></div><div class="field"><label>Provider / organization</label><input id="riProvider" value="${item?.provider||''}" required></div><div class="field"><label>Amount</label><input id="riAmount" type="number" min="0" step=".01" value="${item?.amount||''}" required></div><div class="field"><label>Frequency</label><select id="riFrequency">${frequencyOptions(item?.frequency||'monthly')}</select></div><div class="field"><label>Next due date</label><input id="riDue" type="date" value="${item?.nextDueDate||''}" required></div><div class="field"><label>Payment account</label><select id="riAccount">${accountOptions(item?.paymentAccountId)}</select></div><div class="field full"><label>Cancellation / service / organization link</label><input id="riUrl" type="url" value="${item?.serviceUrl||''}" placeholder="https://"></div>${type!=='utility'?`<div class="field full"><label>Logo image link (optional)</label><input id="riLogo" type="url" value="${item?.logoUrl||''}" placeholder="https://... image URL"></div>`:''}<div class="field full"><label><input id="riAutopay" type="checkbox" ${item?.autopay?'checked':''}> Autopay enabled</label></div>`,()=>{const record=item||{id:type+'-'+Date.now(),type};Object.assign(record,{name:$('#riName').value.trim(),provider:$('#riProvider').value.trim(),amount:Number($('#riAmount').value),frequency:$('#riFrequency').value,nextDueDate:$('#riDue').value,paymentAccountId:$('#riAccount').value,autopay:$('#riAutopay').checked,serviceUrl:$('#riUrl').value.trim(),logoUrl:type==='utility'?'':($('#riLogo').value.trim())});if(!item)state.recurringItems.push(record);dataProvider.save(state);renderRecurringPages();showToast(record.name+' saved.')})};
    const utilityIconFor=item=>{const text=(item.name+' '+item.provider).toLowerCase();return text.includes('water')?'droplets':text.includes('electric')?'zap':text.includes('solar')?'sun':text.includes('internet')||text.includes('fiber')?'wifi':text.includes('phone')||text.includes('mobile')?'smartphone':text.includes('garbage')||text.includes('waste')?'trash-2':'plug-zap'},recurringVisual=item=>item.type==='utility'?'<div class="utility-service-icon" title="'+item.name+' utility"><i data-lucide="'+utilityIconFor(item)+'"></i></div>':item.logoUrl?'<div class="recurring-logo"><img src="'+item.logoUrl+'" alt="'+item.name+' logo"></div>':'<div class="recurring-logo" title="Logo image link can be added while editing">No logo</div>';
    const recurringCard=item=>'<article class="card recurring-card"><div class="inventory-top">'+recurringVisual(item)+'<span class="inventory-badge '+(item.autopay?'autopay-on':'autopay-off')+'">'+(item.autopay?'Autopay':'Manual pay')+'</span></div><div class="recurring-amount">'+money(item.amount)+'</div><h2>'+item.name+'</h2><div class="card-note">'+item.provider+' · '+item.frequency+'</div><div class="recurring-meta"><div class="recurring-meta-row"><span>Monthly equivalent</span><strong>'+money(monthlyValue(item))+'</strong></div><div class="recurring-meta-row"><span>Next due</span><strong>'+new Date(item.nextDueDate+'T12:00').toLocaleDateString('en-US')+'</strong></div><div class="recurring-meta-row"><span>Payment account</span><strong>'+accountName(item.paymentAccountId)+'</strong></div></div><div class="inventory-actions"><button class="secondary-btn" data-edit-recurring="'+item.id+'">Edit</button>'+(item.type==='donation'?'<button class="primary-btn" data-log-recurring-gift="'+item.id+'">Log gift</button>':'')+(item.serviceUrl?'<a class="secondary-btn" target="_blank" rel="noopener" href="'+item.serviceUrl+'">'+(item.type==='donation'?'Organization':'Manage / cancel')+' ↗</a>':'')+'</div></article>';
    const renderRecurringCategory=(page,type)=>{const rows=state.recurringItems.filter(x=>x.type===type),monthly=rows.reduce((n,x)=>n+monthlyValue(x),0),annual=rows.reduce((n,x)=>n+annualValue(x),0);page.querySelector('[data-monthly-total]').textContent=money(monthly);page.querySelector('[data-annual-total]').textContent=money(annual);page.querySelector('[data-active-count]').textContent=rows.length;page.querySelector('[data-autopay-count]').textContent=rows.filter(x=>x.autopay).length;page.querySelector('[data-upcoming]').innerHTML=rows.slice().sort((a,b)=>a.nextDueDate.localeCompare(b.nextDueDate)).slice(0,4).map(x=>'<div class="upcoming-charge"><strong>'+x.name+'</strong><div class="sub">'+new Date(x.nextDueDate+'T12:00').toLocaleDateString('en-US')+' · '+money(x.amount)+'</div></div>').join('');page.querySelector('[data-recurring-list]').innerHTML=rows.map(recurringCard).join('');page.querySelector('[data-recurring-new]').onclick=()=>openRecurringEditor(type);page.querySelectorAll('[data-edit-recurring]').forEach(b=>b.onclick=()=>openRecurringEditor(type,b.dataset.editRecurring))};
    const openDonationEntry=(kind='cash',id,recurringId)=>{const entry=id?state.donationEntries.find(x=>x.id===id):null,recurring=state.recurringItems.find(x=>x.id===(recurringId||entry?.recurringId));openSimpleData(entry?'Edit donation record':kind==='in-kind'?'Record in-kind donation':'Record cash donation','Personal recordkeeping only; no tax calculation or tax-reporting logic is applied.',`<div class="field"><label>Giving type</label><select id="dgKind"><option value="cash" ${(entry?.kind||kind)==='cash'?'selected':''}>One-time cash</option><option value="in-kind" ${(entry?.kind||kind)==='in-kind'?'selected':''}>In-kind</option><option value="recurring" ${(entry?.kind||kind)==='recurring'?'selected':''}>Recurring payment</option></select></div><div class="field"><label>Organization</label><input id="dgOrganization" value="${entry?.organization||recurring?.provider||''}" required></div><div class="field"><label>Date</label><input id="dgDate" type="date" value="${entry?.date||new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Cash amount / estimated in-kind value</label><input id="dgAmount" type="number" min="0" step=".01" value="${entry?.amount||recurring?.amount||''}" required></div><div class="field full"><label>Description</label><textarea id="dgDescription" required>${entry?.description||recurring?.name||''}</textarea></div><div class="field full"><label>Receipt / acknowledgment image link (optional)</label><input id="dgReceipt" type="url" value="${entry?.receiptUrl||''}" placeholder="https://"></div>`,()=>{const record=entry||{id:'donation-'+Date.now()};Object.assign(record,{kind:$('#dgKind').value,organization:$('#dgOrganization').value.trim(),date:$('#dgDate').value,amount:Number($('#dgAmount').value),description:$('#dgDescription').value.trim(),receiptUrl:$('#dgReceipt').value.trim(),recurringId:recurringId||entry?.recurringId||''});if(!entry)state.donationEntries.push(record);dataProvider.save(state);renderRecurringPages();showToast('Donation record saved.')})};
    const givingEntry=e=>'<div class="giving-entry"><div class="giving-kind"><i data-lucide="'+(e.kind==='in-kind'?'package':'hand-coins')+'"></i></div><div><strong>'+e.organization+'</strong><div class="sub">'+new Date(e.date+'T12:00').toLocaleDateString('en-US')+' · '+e.description+'</div>'+(e.receiptUrl?'<a class="receipt-link" target="_blank" rel="noopener" href="'+e.receiptUrl+'">Receipt / acknowledgment ↗</a>':'')+'</div><div style="text-align:right"><strong>'+money(e.amount)+'</strong><br><button class="link-btn" data-edit-donation="'+e.id+'">Edit</button></div></div>';
    renderRecurringPages=function(){renderRecurringCategory(subscriptionsPage,'subscription');renderRecurringCategory(utilitiesPage,'utility');const recurring=state.recurringItems.filter(x=>x.type==='donation'),year=String(new Date().getFullYear()),ytd=state.donationEntries.filter(e=>e.date.startsWith(year)),cash=ytd.filter(e=>e.kind!=='in-kind').reduce((n,e)=>n+Number(e.amount),0),inKind=ytd.filter(e=>e.kind==='in-kind').reduce((n,e)=>n+Number(e.amount),0);$('#givingYtd').textContent=money(cash+inKind);$('#givingCashYtd').textContent=money(cash);$('#givingInKindYtd').textContent=money(inKind);$('#givingRecurringMonthly').textContent=money(recurring.reduce((n,e)=>n+monthlyValue(e),0));$('#recurringGivingList').innerHTML=recurring.map(recurringCard).join('');$('#cashGivingList').innerHTML=state.donationEntries.filter(e=>e.kind==='cash').sort((a,b)=>b.date.localeCompare(a.date)).map(givingEntry).join('')||'<div class="sub">No one-time cash gifts recorded.</div>';$('#inKindGivingList').innerHTML=state.donationEntries.filter(e=>e.kind==='in-kind').sort((a,b)=>b.date.localeCompare(a.date)).map(givingEntry).join('')||'<div class="sub">No in-kind gifts recorded.</div>';$$('#recurringGivingList [data-edit-recurring]').forEach(b=>b.onclick=()=>openRecurringEditor('donation',b.dataset.editRecurring));$$('[data-log-recurring-gift]').forEach(b=>b.onclick=()=>openDonationEntry('recurring',null,b.dataset.logRecurringGift));$$('[data-edit-donation]').forEach(b=>b.onclick=()=>openDonationEntry('cash',b.dataset.editDonation));lucide.createIcons()};
    $('#newRecurringDonationBtn').onclick=()=>openRecurringEditor('donation');$('#newDonationEntryBtn').onclick=()=>openDonationEntry('cash');$$('[data-gift-kind]').forEach(b=>b.onclick=()=>openDonationEntry(b.dataset.giftKind));
    const baseSetPageRecurring=setPage;setPage=function(page){[subscriptionsPage,utilitiesPage,donationsPage].forEach(p=>p.classList.remove('active'));baseSetPageRecurring(page);const match=page==='Subscriptions'?subscriptionsPage:page==='Utilities'?utilitiesPage:page==='Charitable Donations'?donationsPage:null;if(match){$('#placeholder').classList.remove('active');match.classList.add('active');$('#pageTitle').textContent=page;renderRecurringPages()}};
    const charityButton=$('.nav button[data-page="Charitable Donations"]');if(charityButton)charityButton.onclick=()=>setPage('Charitable Donations');
    dataProvider.save(state);['Subscriptions','Utilities','Charitable Donations'].forEach(page=>CoreValleyModules.register(page,()=>renderRecurringPages()));lucide.createIcons();
  }
  installRecurringHouseholdPages();
  function installSubscriptionPayoffScenarios(){
    document.head.insertAdjacentHTML('beforeend',`<style>.cancellation-scenario{margin-top:16px}.scenario-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.scenario-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:15px 0}.scenario-stat{background:#f7f9f8;border:1px solid var(--line);border-radius:12px;padding:12px}.scenario-stat strong{display:block;font:800 20px Manrope;margin-top:3px}.scenario-list{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.scenario-option{display:flex;align-items:center;gap:11px;padding:12px;border:1px solid var(--line);border-radius:12px;background:#fff;cursor:pointer}.scenario-option:has(input:checked){border-color:#8cbda9;background:var(--mint)}.scenario-option input{width:17px;height:17px;accent-color:var(--brand)}.scenario-option span{min-width:0;flex:1}.scenario-option .scenario-cost{font-weight:800;color:var(--brand-2);white-space:nowrap}.scenario-note{font-size:9px;color:var(--muted);margin-top:12px}@media(max-width:760px){.scenario-head{display:block}.scenario-summary,.scenario-list{grid-template-columns:1fr}}</style>`);
    state.payoffSubscriptionScenarios=state.payoffSubscriptionScenarios||{};
    const scenarioCard=document.createElement('article');scenarioCard.className='card cancellation-scenario';scenarioCard.id='subscriptionPayoffScenarios';
    const controlCard=$('#engageBar').closest('article');controlCard.after(scenarioCard);
    const frequencyMultiplier={weekly:52,biweekly:26,monthly:12,quarterly:4,semiannual:2,annual:1};
    const monthlyCost=item=>Number(item.amount||0)*(frequencyMultiplier[item.frequency]||12)/12;
    const activeSubscriptions=()=>state.recurringItems.filter(item=>item.type==='subscription'&&item.active!==false&&item.isArchived!==true);
    const scenarioBudget=()=>activeSubscriptions().filter(item=>state.payoffSubscriptionScenarios[item.id]===true).reduce((total,item)=>total+monthlyCost(item),0);
    const originalSimulatePlan=simulatePlan;
    simulatePlan=function(method=state.payoffMethod,extra=Number(state.payoffExtra)||0,rollover=state.payoffRollover!==false){return originalSimulatePlan(method,Number(extra||0)+scenarioBudget(),rollover)};
    const originalGetPayoffPlan=getPayoffPlan;
    getPayoffPlan=function(){const plan=originalGetPayoffPlan(),first=plan.included[0],budget=scenarioBudget();if(first)plan.targets[first.id]=Math.min(first.balance,first.minimum+(Number(state.payoffExtra)||0)+budget);return plan};
    const renderScenarios=()=>{
      const subscriptions=activeSubscriptions(),budget=scenarioBudget(),baseline=originalSimulatePlan(state.payoffMethod,Number(state.payoffExtra)||0,state.payoffRollover!==false),scenario=simulatePlan(),monthsSooner=Math.max(0,baseline.months-scenario.months),interestSaved=Math.max(0,baseline.interest-scenario.interest);
      scenarioCard.innerHTML=`<div class="scenario-head"><div><h2>Subscription cancellation scenarios</h2><div class="card-note">Optionally test how redirecting selected subscription costs to debt changes this payoff projection.</div></div><span class="inventory-badge">Optional · all off by default</span></div><div class="scenario-summary"><div class="scenario-stat"><span class="kpi-label">Added monthly payoff</span><strong>${money(budget)}</strong></div><div class="scenario-stat"><span class="kpi-label">Projected time saved</span><strong>${monthsSooner} month${monthsSooner===1?'':'s'}</strong></div><div class="scenario-stat"><span class="kpi-label">Projected interest saved</span><strong>${money(interestSaved)}</strong></div></div><div class="scenario-list">${subscriptions.map(item=>`<label class="scenario-option"><input type="checkbox" data-subscription-scenario="${item.id}" ${state.payoffSubscriptionScenarios[item.id]===true?'checked':''}><span><strong>${item.name}</strong><span class="sub" style="display:block">${item.provider} · ${item.frequency}</span></span><span class="scenario-cost">+${money(monthlyCost(item))}/mo</span></label>`).join('')||'<div class="sub">No active subscriptions are available for a cancellation scenario.</div>'}</div><div class="scenario-note">Planning scenario only. Selecting an item does not cancel the service or modify its Subscription record. Utilities and charitable donations are excluded.</div>`;
      $$('[data-subscription-scenario]').forEach(input=>input.onchange=()=>{state.payoffSubscriptionScenarios[input.dataset.subscriptionScenario]=input.checked;dataProvider.save(state);renderPayoffPlan()});
      lucide.createIcons();
    };
    const originalRenderPayoffPlan=renderPayoffPlan;
    renderPayoffPlan=function(){originalRenderPayoffPlan();const plan=getPayoffPlan();$('#planPayment').textContent=money(plan.included.reduce((sum,debt)=>sum+debt.minimum,0)+(Number(state.payoffExtra)||0)+scenarioBudget());renderScenarios()};
    CoreValleyModules.register('Debt Payoff Simulator',()=>renderPayoffPlan());
  }
  installSubscriptionPayoffScenarios();
